### ISSUE TITLE
Should we reserve the namespace for sub-objects in our state?

### ISSUE THREAD

**Issue by athanclark** [Download/redux-apis#5]
In the `.getState()` function, there's [a call to](https://github.com/Download/redux-apis/blob/master/src/redux-apis.jsx#L27) `this.__link(this.__parent.getState())` - likewise, in `link()`'s default definition, if `child` isn't defined (like in the call earlier), yet the parent object will be an object and the `this` parameter is still bound to the child, which _does_ have the `.__parent` parameter, which then takes [this code path](https://github.com/Download/redux-apis/blob/master/src/redux-apis.jsx#L84).

Because we're only supplying the parent's `.__state` property to the child's `.__link()`, it would expect it's name to exist in the _state_ of the parent.

How should this work / how should I be doing this?

**Comment by Download** [comment]
@athanclark  Can you have a look at the updated documentation on link and see if it clears up your questions? If not, feel free to re-open.
